# -*- coding: utf-8 -*-
"""forms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEWL9fk7HZ1YPu7q-iCKM5RSxrZpYbqU
"""

import streamlit as st
import pandas as pd
import os

st.title("📋 Formulario de Registro")

# Campos del formulario
nombre = st.text_input("Nombre completo")
edad = st.number_input("Edad", 0, 120)
correo = st.text_input("Correo electrónico")
comentario = st.text_area("Comentario")

# Nombre del archivo donde se guardarán las respuestas
archivo = "respuestas.csv"

if st.button("Enviar"):
    nueva_respuesta = pd.DataFrame({
        'Nombre': [nombre],
        'Edad': [edad],
        'Correo': [correo],
        'Comentario': [comentario]
    })

    if os.path.exists(archivo):
        df_existente = pd.read_csv(archivo)
        df_actualizado = pd.concat([df_existente, nueva_respuesta], ignore_index=True)
    else:
        df_actualizado = nueva_respuesta

    df_actualizado.to_csv(archivo, index=False)
    st.success("✅ ¡Gracias por enviar tu respuesta!")

# Mostrar todas las respuestas (opcional)
if st.checkbox("Mostrar respuestas"):
    if os.path.exists(archivo):
        st.write(pd.read_csv(archivo))
    else:
        st.write("Aún no hay respuestas.")